_angeldress/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from sitemaps import (
    StaticViewSitemap,
    PostSitemap,
    DressSitemap,
)

sitemaps = {
    'static': StaticViewSitemap,
    'posts': PostSitemap,
    'dresses': DressSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app_home.urls")),
    path("catalog/", include("app_catalog.urls")),
    path("blog/", include("app_blog.urls")),
    path("wishlist/", include("app_wishlist.urls")),
    path("book/", include("app_book.urls")),
    path("callback/", include("app_client_call_back.urls")),
    path("newsletter/", include("app_newsletter.urls")),
    path("promo/", include("app_promotion.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="django.contrib.sitemaps.views.sitemap",),
    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_blog/urls.py
from django.urls import path

from app_blog.views import blog_view, post_view, posts_by_tag

app_name = 'app_blog'
urlpatterns = [
    path('', blog_view, name='blog'),
    path('post/<int:post_id>/', post_view, name='post'),
    path('tag/<slug:tag_slug>/', posts_by_tag, name='posts_by_tag'),
]

app_blog/models.py
import os

from django.db import models
from django.urls import reverse
from django.utils.text import slugify

from app_home.models import SocialTypes


class Author(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"


class AuthorSocial(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, null=True, blank=True)
    type = models.ForeignKey(SocialTypes, on_delete=models.SET_NULL, null=True)
    link = models.URLField("Ссылка", blank=True, null=True)

    def __str__(self):
        return f"{self.author.name} - {self.type.get_name_display()}"

    class Meta:
        verbose_name = "Социальная сеть"
        verbose_name_plural = "Социальные сети"


class Tag(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50, unique=True, null=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    class Meta:
        verbose_name = "Тег"
        verbose_name_plural = "Теги"


class Post(models.Model):
    title = models.CharField(max_length=255)
    tags = models.ManyToManyField(Tag, related_name="posts")
    content = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to="blog_images/", null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def delete(self, *args, **kwargs):
        if self.image:
            if os.path.isfile(self.image.path):
                os.remove(self.image.path)
        super(Post, self).delete(*args, **kwargs)

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def get_absolute_url(self):
        return reverse("app_blog:post", args=[self.id])

app_blog/forms.py
from django import forms
from ckeditor.widgets import CKEditorWidget
from .models import Post

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = "__all__"
        widgets = {"content": CKEditorWidget()}

app_blog/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.utils.html import strip_tags
from django.utils.text import Truncator

from app_blog.models import Post, Tag


def blog_view(request):
    # Получаем все посты, отсортированные по дате создания (новые сначала)
    posts_list = Post.objects.all().order_by('-created_at')

    # Пагинация - 9 постов на страницу (как в каталоге)
    paginator = Paginator(posts_list, 9)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,  # Для совместимости с пагинацией
        'meta_description': "Актуальные новости и статьи о моде, свадьбах и событиях от Angel Dress",
        'title': 'Блог'
    }
    return render(request, 'app_blog/blog.html', context)


def post_view(request, post_id):
    post = get_object_or_404(Post, id=post_id)

    # Очищаем от HTML-тегов и обрезаем текст
    clean_content = strip_tags(post.content)
    truncated_content = Truncator(clean_content).words(20)

    meta_description = f"{post.title}. {truncated_content}"

    context = {
        'post': post,
        'meta_description': meta_description,
        'title': post.title
    }
    return render(request, 'app_blog/post.html', context)


def posts_by_tag(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    posts = Post.objects.filter(tags=tag)
    context = {
        'tag': tag,
        'posts': posts,
        'meta_description': "Актуальные новости и статьи о моде, свадьбах и событиях от Angel Dress",
    }
    return render(request, 'app_blog/posts_by_tag.html', context)

templates/app_blog/blog.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{{% block title %}
    <title>{{ title|default:"Новости | Angel Dress" }}</title>
    <meta name="description" content="{{ meta_description }}">
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <link rel="stylesheet" href="{% static 'styles/blog.css' %}">
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="blog-container">
            <main class="blog-content">
                <h1 class="page-main-title">Новости</h1>

                {% if page_obj %}
                    {% for post in page_obj %}
                        <div class="blog-card">
                            <div class="blog-text-content">
                                <h2 class="blog-title">{{ post.title }}</h2>

                                <div class="post-meta">
                                    {% if post.tags.all %}
                                        <div class="tags">
                                            {% for tag in post.tags.all %}
                                                <a href="{% url 'app_blog:posts_by_tag' tag.slug %}"
                                                   class="tag">{{ tag.name }}</a>
                                            {% endfor %}
                                        </div>
                                    {% endif %}
                                </div>

                                <p class="blog-description">
                                    {{ post.content|safe|striptags|truncatewords:30 }}
                                </p>

                                <a class="open-button" href="{% url 'app_blog:post' post.id %}">Читать</a>
                            </div>

                            {% if post.image %}
                                <div class="blog-image">
                                    <img src="{{ post.image.url }}" alt="{{ post.title }}">
                                </div>
                            {% else %}
                                <div class="blog-image">
                                    <img src="{% static 'img/No-Image-Placeholder.png' %}"
                                         alt="Изображение отсутствует">
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% else %}
                    <div class="no-posts">
                        <p>Статей пока нет, но они скоро появятся</p>
                    </div>
                {% endif %}
            </main>
        </div>

        {% include 'includes/pagination.html' %}
    </div>
{% endblock %}

templates/app_blog/post.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>{{ post.title }} | Блог Angel Dress</title>
    <meta name="description" content="{{ meta_description }}">
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <link rel="stylesheet" href="{% static 'styles/blog.css' %}">
{% endblock %}

{% block content %}
    <div class="wrapper">
        <div class="post-container">
            <main class="post-content">
                <article class="post-article">
                    <div class="post-header">
                        <div class="post-date">
                            <span class="day">{{ post.created_at|date:"d" }}</span>
                            <span class="month">{{ post.created_at|date:"M" }}</span>
                        </div>
                        <h1 class="post-title">{{ post.title }}</h1>
                    </div>

                    {% if post.image %}
                        <div class="post-image-wrapper">
                            <img src="{{ post.image.url }}" alt="{{ post.title }}" class="post-image">
                        </div>
                    {% endif %}

                    <div class="post-text-block">
                        {{ post.content|safe }}
                    </div>

                    <div class="post-footer">
                        <div class="post-meta">
                            <p class="post-footer-date"><span class="post-footer-date-text">Опубликовано: {{ post.created_at|date:"d.m.Y" }}</span></p>
                            
                            {% if post.tags.all %}
                                <div class="tags">
                                    {% for tag in post.tags.all %}
                                        <a href="{% url 'app_blog:posts_by_tag' tag.slug %}"
                                           class="tag">{{ tag.name }}</a>
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>

                    <a href="{% url 'app_blog:blog' %}" class="back-to-blog">
                        ← Все статьи
                    </a>
                </article>
            </main>
        </div>
    </div>
{% endblock %}

templates/app_blog/posts_by_tag.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}


{{% block title %}
    <title>{{ title|default:"Блог | Angel Dress" }}</title>
    <meta name="description" content="{{ meta_description }}">
{% endblock %}


{% block styles %}
    <link rel="stylesheet" href="{% static 'styles/styles.css' %}">
    <link rel="stylesheet" href="{% static 'styles/blog.css' %}">
{% endblock %}


{% block content %}
    <div class="wrapper">
        <div class="blog-container">
            <h1>Посты с тегом: {{ tag.name }}</h1>

            <div class="blog-content">
                {% for post in posts %}
                    <div class="blog-card">
                        <div class="blog-text-content">
                            <h2 class="blog-title">{{ post.title }}</h2>

                            <div class="post-meta">
                                {% if post.tags.all %}
                                    <div class="tags">
                                        {% for tag in post.tags.all %}
                                            <a href="{% url 'app_blog:posts_by_tag' tag.slug %}"
                                               class="tag">{{ tag.name }}</a>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            </div>

                            <p class="blog-description">
                                {{ post.content|striptags|truncatewords:30 }}
                            </p>

                            <a class="open-button" href="{% url 'app_blog:post' post.id %}">Читать</a>
                        </div>

                        {% if post.image %}
                            <div class="blog-image">
                                <img src="{{ post.image.url }}" alt="{{ post.title }}">
                            </div>
                        {% else %}
                            <div class="blog-image">
                                <img src="{% static 'img/No-Image-Placeholder.png' %}" alt="Изображение отсутствует">
                            </div>
                        {% endif %}
                    </div>
                {% empty %}
                    <p>Нет постов с этим тегом.</p>
                {% endfor %}
            </div>

            <a href="{% url 'app_blog:blog' %}" class="back-to-blog">
                ← Все статьи
            </a>
        </div>
    </div>
{% endblock %}